# Generated by Django 5.2.6 on 2025-10-15 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_alquiler', models.DateTimeField()),
                ('fecha_hora_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'alquileres',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('domicilio_cli', models.CharField(max_length=200)),
                ('localidad_cli', models.CharField(max_length=100)),
                ('dni_cli', models.CharField(max_length=20)),
                ('email_cli', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('ingreso_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egreso_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_entrega', models.DateTimeField()),
                ('direccion', models.CharField(max_length=200)),
                ('estado_entrega', models.CharField(max_length=50)),
                ('responsable_entrega', models.CharField(max_length=100)),
                ('alquiler', models.ForeignKey(db_column='id_alquiler', on_delete=django.db.models.deletion.CASCADE, to='core.alquiler')),
            ],
            options={
                'db_table': 'entregas',
            },
        ),
        migrations.CreateModel(
            name='DetEntrega',
            fields=[
                ('id_det_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('empleado', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('entrega', models.ForeignKey(db_column='id_entregas', on_delete=django.db.models.deletion.CASCADE, to='core.entrega')),
            ],
            options={
                'db_table': 'det_entregas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='core.caja')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ped', models.DateField()),
                ('fecha_hora_evento', models.DateTimeField()),
                ('fecha_hora_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado_ped', models.CharField(max_length=50)),
                ('total_ped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=50)),
                ('alquiler', models.ForeignKey(blank=True, db_column='id_alquiler', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alquiler')),
                ('cliente', models.ForeignKey(db_column='id_clientes', on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('empleado', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_factura', models.CharField(max_length=50)),
                ('pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, to='core.pago')),
                ('pedido', models.ForeignKey(db_column='id_pedidos', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_productos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_producto', models.BinaryField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_incidente', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado_incidente', models.CharField(default='Abierto', max_length=50)),
                ('alquiler', models.ForeignKey(blank=True, db_column='id_alquiler', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alquiler')),
                ('producto', models.ForeignKey(db_column='id_productos', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'db_table': 'incidentes',
            },
        ),
        migrations.CreateModel(
            name='DetPedido',
            fields=[
                ('id_det_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(db_column='id_pedidos', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('producto', models.ForeignKey(db_column='id_productos', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'db_table': 'det_pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetAlquiler',
            fields=[
                ('id_det_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler', models.ForeignKey(db_column='id_alquiler', on_delete=django.db.models.deletion.CASCADE, to='core.alquiler')),
                ('producto', models.ForeignKey(db_column='id_productos', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'db_table': 'det_alquileres',
            },
        ),
    ]
